module.exports = {
/*  ACCOUNT: 'account',
  EMPLOYEE: 'employee',
  EMPLOYEES: 'employees',
  STUDENT: 'student',
  STUDENTS: 'students',
  INSTITUTION: 'institution',
  INSTITUTIONS: 'institutions',
  MAJOR: 'major',
  MAJORS: 'majors',
  LEARNING_OUTCOME: 'learning outcome',
  LEARNING_OUTCOMES: 'learning outcomes',
  PARENT: 'parent',
  COURSE: 'course',
  COURSE_CODE: 'course_code',
  COURSE_CODES: 'course_codes',
  TRAINING_PROGRAM: 'training program',
  OUTLINE: 'outline',
  DOCUMENT: 'document.png',
  TICKETS: 'tickets',*/

  ACCOUNT: 'tài khoản',
  EMPLOYEE: 'giảng viên',
  EMPLOYEES: 'danh sách giảng viên',
  STUDENT: 'sinh viên',
  STUDENTS: 'danh sách sinh viên',
  INSTITUTION: 'đơn vị chuyên môn',
  INSTITUTIONS: 'danh sách đơn vị chuyên môn',
  MAJOR: 'ngành',
  MAJORS: 'danh sách ngành',
  LEARNING_OUTCOME: 'chuẩn đầu ra',
  LEARNING_OUTCOMES: 'danh sách chuẩn đầu ra',
  PARENT: 'danh mục chuẩn đầu ra',
  COURSE: 'học phần',
  COURSE_CODE: 'mã học phần',
  COURSE_CODES: 'danh sách mã học phần',
  TRAINING_PROGRAM: 'chương trình đào tạo',
  OUTLINE: 'đề cương học phần',
  DOCUMENT: 'tài liệu',
  TICKETS: 'các yêu cầu cập nhật đề cương',
  TYPE: 'hệ chương trình đào tạo',

  UUID: 'uuid',
  USERNAME: 'username',
  ACCESS_TOKEN: 'access_token',
  ROLE: 'role',
  ORDER: 'order',
  ASC: 'ASC',

  DEFAULT_PAGE_VALUE: 1,
  TOKEN_EXPIRES: 24 * 60 * 60 * 1000, //1 month in miliseconds
  SALT_ROUND: 10
}
